import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import {createClient} from '@supabase/supabase-js';
const env=Object.fromEntries((await fs.readFile('.env.local','utf8')).split(/\r?\n/).filter(l=>l.trim()&&!l.startsWith('#')).map(l=>{const i=l.indexOf('=');return[l.slice(0,i),l.slice(i+1).replace(/^['"]|['"]$/g,'')];}));
const accounts=JSON.parse(await fs.readFile('.local-private/remote-test-accounts.json','utf8'));
if(env.NEXT_PUBLIC_SUPABASE_URL!=='https://bnqyyumfmyexsqszglab.supabase.co'||accounts.projectRef!=='bnqyyumfmyexsqszglab')throw new Error('Proyecto no autorizado');
const client=()=>createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??env.NEXT_PUBLIC_SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const anon=client(),clients={};const report={startedAt:new Date().toISOString(),migration:'scoped-and-private-lock',checks:[],limitations:['Datos ficticios; no mide capacidad ni entrega de correo.','Los permisos SQL internos se verifican adicionalmente con SET ROLE en PostgreSQL aislado.']};
const ok=(value,name)=>{if(!value)throw new Error(name);report.checks.push({name,result:'passed'});console.log(`PASS ${name}`);};
const rpc=async(c,name,args={})=>{const {data,error}=await c.rpc(name,args);if(error)throw error;if(data?.error)throw data.error;return data;};
const command=(c,action,...args)=>rpc(c,'aulify_command',{p_action:action,p_payload:{args}});
const deny=async(fn,name)=>{try{await fn();throw new Error('unexpected-success');}catch(e){if(e.message==='unexpected-success'||['42702','42703','42883','42P01'].includes(e.code))throw e;ok(true,name);}};
try{
 for(const name of ['teacher','teacherOther','student','studentOther']){const c=client();const {error}=await c.auth.signInWithPassword({email:accounts.users[name].email,password:accounts.users[name].password});if(error)throw error;clients[name]=c;}
 const {teacher,teacherOther,student,studentOther}=clients;
 const subject=await command(teacher,'createSubject',{name:'Sincronización acotada · prueba',course:'Prueba',year:2026,description:'Datos ficticios'});
 report.subjectId=subject.id;
 const full=await rpc(teacher,'aulify_snapshot'),code=full.state.subjects.find(s=>s.id===subject.id).code;
 const id=()=>crypto.randomUUID(),options=[{id:id(),text:'Primera'},{id:id(),text:'Segunda'}];
 const questions=[{id:id(),type:'single',prompt:'Escoge',points:5,options,correctOptionId:options[0].id,explanation:'SOLUCION_PRIVADA_SCOPE'},{id:id(),type:'open',prompt:'Explica',points:5,manual:true,manualGuide:'GUIA_PRIVADA_SCOPE'}];
 const draft={id:id(),ownerId:accounts.users.teacher.id,title:'Recurso para sincronización',kind:'quiz',blocks:[{id:id(),type:'quiz',questions}],revision:1,updatedAt:new Date().toISOString()};
 await command(teacher,'saveDraft',draft,0);const version=await command(teacher,'publishResource',draft.id);
 const settings={purpose:'practice',pace:'individual',maxGrade:100,weight:1,countsTowardAverage:true,maxAttempts:2,opensAt:new Date(Date.now()-60000).toISOString(),closesAt:new Date(Date.now()+3600000).toISOString(),timeLimitMinutes:null,timeZone:'America/La_Paz',feedback:'hidden',manualCorrection:false,shuffleQuestions:false,shuffleOptions:false,streaks:false,sound:false,ranking:false,teams:false,allowHint:false,allowDouble:false,bonusAffectsGrade:false,reportVisibility:true};
 const activity=await command(teacher,'createActivity',version.id,subject.id,settings,'Sincronización segura');report.activityId=activity.id;
 const scope=c=>rpc(c,'aulify_activity_snapshot',{p_activity_id:activity.id}),sync=c=>rpc(c,'aulify_sync',{p_activity_id:activity.id});
 await deny(()=>scope(anon),'Anónimo no lee actividad');await deny(()=>scope(teacherOther),'Docente ajeno no lee actividad');await deny(()=>scope(student),'Estudiante no inscrito no lee actividad');
 for(const c of [student,studentOther]){const request=await command(c,'requestMembership',code);await command(teacher,'decideMembership',request.id,'approved');}
 let ts=await scope(teacher);ok(ts.state.activities.length===1&&ts.state.subjects.length===1&&ts.state.versions.length===1&&ts.state.resources.length===0,'Docente solo recibe ámbito solicitado');
 let ss=await scope(student);ok(ss.state.users.length===1&&ss.state.versions.length===0&&Object.keys(ss.studentActivities).length===1,'Estudiante recibe solo identidad y proyección propia');
 ok(!JSON.stringify(ss).includes('SOLUCION_PRIVADA_SCOPE')&&!JSON.stringify(ss).includes('GUIA_PRIVADA_SCOPE')&&!JSON.stringify(ss).includes('correctOptionId'),'Proyección acotada sin soluciones privadas');
 ok(ss.state.tasks.length===0&&ss.state.manualActivities.length===0&&Object.keys(ss.studentResults).length===0,'Ámbito omite módulos externos a la actividad');
 const unchanged=(await sync(student)).revision;ok(unchanged===(await sync(student)).revision,'Huella estable sin cambios');
 const teacherBefore=(await sync(teacher)).revision;
 const peer=await command(studentOther,'startAttempt',activity.id);await command(studentOther,'submitAnswer',peer.id,questions[0].id,{type:'single',optionId:options[0].id},id(),false);
 ok(unchanged===(await sync(student)).revision,'Respuesta ajena no altera huella estudiantil');ok(teacherBefore!==(await sync(teacher)).revision,'Participación altera huella docente');
 const attempt=await command(student,'startAttempt',activity.id);const k=id();
 const answer=await command(student,'submitAnswer',attempt.id,questions[0].id,{type:'single',optionId:options[0].id},k,false);ok(answer.feedback===null,'ACK no expone acierto oculto');
 const replay=await command(student,'submitAnswer',attempt.id,questions[0].id,{type:'single',optionId:options[0].id},k,false);ok(replay.attempt.answers.length===1,'Reintento idempotente no duplica respuesta');
 await command(student,'submitAnswer',attempt.id,questions[1].id,{type:'open',text:'Explicación ficticia'},id(),false);
 const beforeReview=(await sync(student)).revision;
 await command(teacher,'reviewAnswer',attempt.id,questions[1].id,4,'Comentario todavía privado');
 ok(beforeReview===(await sync(student)).revision,'Corrección privada no altera huella');ss=await scope(student);ok(ss.state.attempts.every(a=>a.answers.every(x=>x.reviews.length===0))&&!JSON.stringify(ss).includes('Comentario todavía privado'),'Corrección privada no aparece en snapshot acotado');
 await command(teacher,'publishGrade',activity.id,accounts.users.student.id);
 ok(beforeReview!==(await sync(student)).revision,'Publicación de nota altera huella');ss=await scope(student);ok(ss.state.evaluations.some(e=>e.grade===90),'Nota publicada visible sin soluciones');
 const guided=await command(teacher,'createActivity',version.id,subject.id,{...settings,pace:'guided',maxAttempts:1},'Sala privada de prueba');
 for(const c of [student,studentOther])await command(c,'joinGuidedRoom',guided.id);
 const room=await rpc(student,'aulify_activity_snapshot',{p_activity_id:guided.id});
 ok(room.state.activities[0].guided.studentIds.length===1&&room.state.activities[0].guided.studentIds[0]===accounts.users.student.id&&!('lockedAt' in room.state.activities[0]),'Sala estudiantil sin UUID ajenos ni bloqueo docente');
 const teacherRoom=await rpc(teacher,'aulify_activity_snapshot',{p_activity_id:guided.id});ok(teacherRoom.state.activities[0].guided.studentIds.length===2&&('lockedAt' in teacherRoom.state.activities[0]),'Docente conserva participantes de sala y bloqueo');
 ts=await scope(teacher);const membership=ts.state.memberships.find(m=>m.studentId===accounts.users.student.id);
 await command(teacher,'withdrawMembership',membership.id,'Comprobación ficticia');await deny(()=>scope(student),'Retiro revoca snapshot inmediatamente');await deny(()=>sync(student),'Retiro revoca huella inmediatamente');
 await command(teacher,'archiveSubject',subject.id);await deny(()=>scope(studentOther),'Archivo revoca acceso estudiantil');ok((await scope(teacher)).state.subjects[0].status==='archived','Propietario puede inspeccionar materia archivada');await command(teacher,'restoreSubject',subject.id);
 const opening=await command(teacher,'createActivity',version.id,subject.id,{...settings,opensAt:new Date(Date.now()+5000).toISOString()},'Frontera de apertura');
 const openingSync=()=>rpc(studentOther,'aulify_sync',{p_activity_id:opening.id});const beforeOpen=await openingSync();
 ok(Date.parse(beforeOpen.nextDeadline)===Date.parse(opening.settings.opensAt),'Próxima frontera es la apertura futura');
 await new Promise(r=>setTimeout(r,Math.max(0,Date.parse(opening.settings.opensAt)-Date.now()+100)));
 ok(beforeOpen.revision!==(await openingSync()).revision,'Apertura cambia huella sin escritura');
 report.status='passed';
}catch(e){report.status='failed';report.failure={code:e.code??e.name,message:e.message};console.error(`Fallo: ${e.code??e.name}: ${e.message}`);process.exitCode=1;}finally{report.completedAt=new Date().toISOString();await fs.writeFile('docs/verificacion/datos-sincronizacion-remota.json',JSON.stringify(report,null,2)+'\n');console.log(`Comprobaciones: ${report.checks.length}.`);}
