-- Ventanas vigentes de reentrega, limitadas al docente propietario y al estudiante autorizado.
create or replace function app.snapshot() returns jsonb language plpgsql security definer set search_path='' as $$
declare u uuid:=app.require_user(); teacher boolean; st jsonb; profiles jsonb; subjects jsonb; members jsonb; resources jsonb; versions jsonb; activities jsonb; attempts jsonb; powers jsonb; evaluations jsonb; tasks jsonb; submissions jsonb; manuals jsonb; help jsonb; studentviews jsonb:='{}'; results jsonb:='{}'; extra jsonb; rec record;
begin
 select role='teacher' into teacher from app.profiles where id=u;
 -- Materializar vencimientos propios o de las materias docentes; no modifica otros ámbitos.
 for rec in select at.id from app.attempts at join app.participants p on p.id=at.participant_id join app.memberships m on m.id=p.membership_id join app.activities a on a.id=p.activity_id where at.closed_at is null and (app.owns_subject(a.subject_id) or m.student_id=u and app.can_subject(a.subject_id)) and app.deadline(a.id,p.id,at.started_at)<=now() loop perform app.close_attempt(rec.id,'deadline'); end loop;
 select coalesce(jsonb_agg(jsonb_build_object('id',pr.id,'name',pr.display_name,'role',pr.role,'email',case when pr.id=u then au.email else '' end)),'[]') into profiles from app.profiles pr join auth.users au on au.id=pr.id where pr.id=u or teacher and exists(select 1 from app.memberships m join app.subjects s on s.id=m.subject_id where m.student_id=pr.id and s.owner_id=u) or teacher and exists(select 1 from app.join_requests jr join app.invitation_codes c on c.id=jr.invitation_id join app.subjects s on s.id=c.subject_id where jr.student_id=pr.id and s.owner_id=u);
 select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('id',s.id,'ownerId',s.owner_id,'name',s.name,'course',s.course_label,'year',s.school_year,'description',s.description,'status',case when s.archived_at is null then 'active' else 'archived' end,'archivedAt',s.archived_at))||jsonb_build_object('code',case when s.owner_id=u then (select code from app.invitation_codes where subject_id=s.id and revoked_at is null) else null end)),'[]') into subjects from app.subjects s where app.can_subject(s.id) or exists(select 1 from app.join_requests jr join app.invitation_codes c on c.id=jr.invitation_id where c.subject_id=s.id and jr.student_id=u and jr.status in ('pending','rejected'));
 select coalesce(jsonb_agg(j),'[]') into members from (
  select jsonb_build_object('id',m.id,'subjectId',m.subject_id,'studentId',m.student_id,'status',case m.status when 'withdrawn' then 'removed' else m.status end,'requestedAt',m.created_at,'decidedAt',m.updated_at) j from app.memberships m where app.owns_subject(m.subject_id,false) or m.student_id=u and app.can_subject(m.subject_id)
  union all select jsonb_build_object('id',jr.id,'subjectId',c.subject_id,'studentId',jr.student_id,'status',jr.status,'requestedAt',jr.requested_at,'decidedAt',jr.decided_at) from app.join_requests jr join app.invitation_codes c on c.id=jr.invitation_id where jr.status in ('pending','rejected') and (app.owns_subject(c.subject_id,false) or jr.student_id=u) and not exists(select 1 from app.memberships m where m.subject_id=c.subject_id and m.student_id=jr.student_id and m.status='approved')
 ) allmembers;
 select coalesce(jsonb_agg(d.document||jsonb_build_object('id',r.id,'ownerId',r.owner_id,'title',r.title,'kind',case r.kind when 'standalone_quiz' then 'quiz' else 'resource' end,'revision',d.revision,'updatedAt',d.updated_at)),'[]') into resources from app.resources r join app.resource_drafts d on d.resource_id=r.id where r.owner_id=u;
 select coalesce(jsonb_agg(app.version_json(v.id,true)),'[]') into versions from app.resource_versions v join app.resources r on r.id=v.resource_id where r.owner_id=u;
 select coalesce(jsonb_agg(app.activity_json(a.id)),'[]') into activities from app.activities a where a.kind='quiz' and (app.owns_subject(a.subject_id,false) or app.can_subject(a.subject_id) and a.published_at is not null);
 select coalesce(jsonb_agg(app.attempt_json(at.id,app.owns_subject(a.subject_id,false))),'[]') into attempts from app.attempts at join app.participants p on p.id=at.participant_id join app.memberships m on m.id=p.membership_id join app.activities a on a.id=p.activity_id where app.owns_subject(a.subject_id,false) or m.student_id=u and app.can_subject(a.subject_id);
 select coalesce(jsonb_agg(jsonb_build_object('activityId',p.activity_id,'studentId',m.student_id,'kind',pu.kind,'questionId',aq.question_key,'attemptId',aq.attempt_id,'at',pu.consumed_at)),'[]') into powers from app.powerup_uses pu join app.participants p on p.id=pu.participant_id join app.memberships m on m.id=p.membership_id join app.activities a on a.id=p.activity_id join app.attempt_questions aq on aq.id=pu.attempt_question_id where app.owns_subject(a.subject_id,false) or m.student_id=u and app.can_subject(a.subject_id);
 select coalesce(jsonb_agg(app.evaluation_json(e.id)),'[]') into evaluations from app.evaluation_revisions e join app.participants p on p.id=e.participant_id join app.memberships m on m.id=p.membership_id join app.activities a on a.id=p.activity_id where e.published_at is not null and (app.owns_subject(a.subject_id,false) or m.student_id=u and app.can_subject(a.subject_id));
 select coalesce(jsonb_agg(app.task_json(a.id)),'[]') into tasks from app.activities a where a.kind='task' and (app.owns_subject(a.subject_id,false) or app.can_subject(a.subject_id) and a.published_at is not null);
 select coalesce(jsonb_agg(app.submission_json(v.id,app.owns_subject(a.subject_id,false))),'[]') into submissions from app.submission_versions v join app.submissions s on s.id=v.submission_id join app.participants p on p.id=s.participant_id join app.activities a on a.id=p.activity_id join app.memberships m on m.id=p.membership_id where app.owns_subject(a.subject_id,false) or m.student_id=u and app.can_subject(a.subject_id);
 select coalesce(jsonb_agg(jsonb_build_object('id',a.id,'subjectId',a.subject_id,'title',a.title,'description',coalesce(a.instructions,''),'occursAt',a.occurs_on,'maxGrade',a.max_grade,'weight',a.weight,'countsTowardAverage',a.counts_for_average)),'[]') into manuals from app.activities a where a.kind='manual' and (app.owns_subject(a.subject_id,false) or app.can_subject(a.subject_id) and a.published_at is not null);
 select coalesce(jsonb_agg(jsonb_build_object('userId',h.profile_id,'version',h.guide_version,'status',h.state)),'[]') into help from app.help_progress h where h.profile_id=u and h.guide_key='initial';
 if not teacher then
  for rec in select a.id from app.activities a where a.kind='quiz' and a.published_at is not null and app.can_subject(a.subject_id) loop studentviews:=studentviews||jsonb_build_object(rec.id,app.student_activity(rec.id)); end loop;
  for rec in select s.id from app.subjects s where app.can_subject(s.id) loop results:=results||jsonb_build_object(rec.id,app.student_results(rec.id)); end loop;
 end if;
 st:=jsonb_build_object('schemaVersion',1,'revision',floor(extract(epoch from clock_timestamp())*1000),'users',profiles,'subjects',subjects,'memberships',members,'resources',resources,'versions',versions,'activities',activities,'attempts',attempts,'powerups',powers,'evaluations',evaluations,'tasks',tasks,'submissions',submissions,'manualActivities',manuals,'helpPreferences',help);
 select jsonb_build_object('incidents',coalesce((select jsonb_agg(to_jsonb(ir)||jsonb_build_object('signalCount',(select count(*) from app.integrity_events where attempt_id=ir.attempt_id))) from app.incident_reviews ir join app.attempts at on at.id=ir.attempt_id join app.participants p on p.id=at.participant_id join app.activities a on a.id=p.activity_id where app.owns_subject(a.subject_id,false)),'[]'::jsonb),'teams',coalesce((select jsonb_agg(jsonb_build_object('id',te.id,'activityId',te.activity_id,'name',te.name,'studentIds',(select jsonb_agg(m.student_id) from app.team_members tm join app.participants p on p.id=tm.participant_id join app.memberships m on m.id=p.membership_id where tm.team_id=te.id))) from app.teams te join app.activities a on a.id=te.activity_id where app.owns_subject(a.subject_id,false)),'[]'::jsonb),'readings',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'subjectId',a.subject_id,'title',a.title,'content',app.version_json(a.version_id,false))) from app.activities a where a.kind='reading' and a.published_at is not null and app.can_subject(a.subject_id)),'[]'::jsonb),'draftEvaluations',coalesce((select jsonb_agg(app.evaluation_json(e.id)) from app.evaluation_revisions e join app.participants p on p.id=e.participant_id join app.activities a on a.id=p.activity_id where app.owns_subject(a.subject_id,false) and e.published_at is null),'[]'::jsonb)) into extra;
 extra:=extra||jsonb_build_object('resubmissionWindows',coalesce((
  select jsonb_agg(jsonb_build_object('taskId',p.activity_id,'studentId',m.student_id,'closesAt',w.closes_at) order by w.closes_at,p.id)
  from app.resubmission_windows w
  join app.participants p on p.id=w.participant_id
  join app.memberships m on m.id=p.membership_id
  join app.activities a on a.id=p.activity_id
  where w.revoked_at is null and now() between w.opens_at and w.closes_at
    and (app.owns_subject(a.subject_id,false) or m.student_id=u and app.can_subject(a.subject_id))
 ),'[]'::jsonb));
 return jsonb_build_object('state',st,'userId',u,'studentActivities',studentviews,'studentResults',results,'participants',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'activityId',p.activity_id,'studentId',m.student_id,'alias','Participante '||lpad(p.alias_no::text,2,'0'))) from app.participants p join app.memberships m on m.id=p.membership_id join app.activities a on a.id=p.activity_id where app.owns_subject(a.subject_id,false)),'[]'::jsonb))||extra;
end $$;
